name: CI-CD Pipeline

# Trigger workflow on push or pull request to main branch
on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  build-test-docker:
    runs-on: ubuntu-latest

    steps:
      # 1 Checkout code
      - uses: actions/checkout@v3

      # 2 Setup Python
      - name: Set up Python 3.10
        uses: actions/setup-python@v4
        with:
          python-version: 3.10

      # 3 Install dependencies
      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt

      # 4 Run tests
      - name: Run tests
        run: |
          pytest

      # 5 Build Docker image
      - name: Build Docker image
        run: |
          docker build -t rammahto1/credit-risk1:latest .

      # 6 Login to Docker Hub
      - name: Log in to Docker Hub
        uses: docker/login-action@v2
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}

      # 7 Push Docker image
      - name: Push Docker image to Docker Hub
        run: |
          docker push rammahto1/credit-risk1:latest
